### ISSUE TITLE
ERR_INVALID_ARG_TYPE(name, 'string', value)

### ISSUE THREAD

**Issue by nikosdrog** [wwwebman/gulp-webpack-starter#54]
Hi guys.
I m getting the bellow error.
Do you have any advice?

Windows 10 PRO
Node v10.16.0
npm 6.9.0

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at Object.<anonymous> (E:\new-bb\demo\config.js:52:56)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)

 Thanks

**Comment by wwwebman** [comment]
Hi, have you followed the instruction? You definitely forgot to add/copy .env file.

This:
> cp .env.dist .env

Or this:
> cp .env.wordpress .env
